build: Unbreak the environment for the Autotools serial test harness
Autotools' serial test harness uses TESTS_ENVIRONMENT, and doesn't
support AM_TESTS_ENVIRONMENT [1]. The latest version of glib-tap.mk in
GLib targets the newer and default parallel test harness, and removing
the "serial-tests" Automake option breaks the graphical test:
  make[5]: Entering directory
    '/home/rishi/devel/gnome-photos/git/gnome-photos/builddir/tests'
  ERROR: basic.py - missing test plan
  tap-driver.sh: internal error getting exit status
  tap-driver.sh: fatal: I/O or internal error
  make[5]: *** [Makefile:1207: basic.py.log] Error 1

Fortunately, there was no significant breakage because the existing
test doesn't use APIs like g_test_build_filename, g_test_get_filename,
and g_test_get_dir, which would have been affected by the missing
G_TEST_BUILDDIR and G_TEST_SRCDIR environment variables.

Since the Autotools build is deprecated, it's easier to stick to the
serial harness instead of trying to fix the graphical test to work with
the parallel setup. Therefore, this partially reverts commit
0ce96a49daf77d4961bf0e4006d96360219278a6 by re-introducing
TESTS_ENVIRONMENT instead of AM_TESTS_ENVIRONMENT.

[1] https://www.gnu.org/software/automake/manual/html_node/Serial-Test-Harness.html#Serial-Test-Harness

https://gitlab.gnome.org/GNOME/gnome-photos/merge_requests/80