tests: Wait for the UI to be drawn completely
The tests sometimes fail with:
  ValueError: Attempting to generate a mouse event at negative
    coordinates: (-2147483647.5,-2147483647.5)

This is because the UI isn't drawn when we try to interact with it.
This is a race condition. We should wait until the x or y coordinate
is valid before going on with the test.

https://bugzilla.gnome.org/show_bug.cgi?id=777053