flatpak: Use secure HTTP wherever possible
Wget reports several TLS errors with exiv2.org:
  Resolving exiv2.org (exiv2.org)... 54.72.225.196
  Connecting to exiv2.org (exiv2.org)|54.72.225.196|:443... connected.
  GnuTLS: A TLS warning alert has been received.
  GnuTLS: received alert [112]: The server name sent was not recognized
  ERROR: The certificate of ‘exiv2.org’ is not trusted.
  ERROR: The certificate of ‘exiv2.org’ hasn't got a known issuer.
  ERROR: The certificate of ‘exiv2.org’ was signed using an insecure
    algorithm.
  The certificate's owner does not match hostname ‘exiv2.org’

Hence it still uses plain HTTP.